package Lexical;// DO NOT EDIT
// Generated by JFlex 1.8.1 http://jflex.de/
// source: myScanner.flex


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class myScanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHAR = 4;
  public static final int ENDCHAR = 6;
  public static final int SPECIALCHARSTR = 8;
  public static final int SPECIALCHAR = 10;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5, 5
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\u10ff\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\3\22\0\1\1\1\4"+
    "\1\5\2\0\2\6\1\7\2\6\1\10\1\11\1\6"+
    "\1\12\1\13\1\14\1\15\11\16\2\6\1\17\1\20"+
    "\1\17\2\0\4\21\1\22\1\21\21\23\1\24\2\23"+
    "\1\6\1\25\2\6\1\23\1\0\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\23\1\37"+
    "\1\40\1\23\1\41\1\42\1\43\1\23\1\44\1\45"+
    "\1\46\1\47\1\50\1\51\1\52\1\53\1\54\1\0"+
    "\1\6\1\0\1\6\u0181\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[512];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\6\0\1\1\1\2\2\3\1\1\1\4\1\5\1\6"+
    "\5\5\2\7\22\10\1\11\1\12\1\13\1\14\1\1"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\0\1\27\3\0\7\10\1\30\5\10"+
    "\2\30\15\10\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\3\0\1\7\12\10\1\30\22\10\1\0\1\27\30\10";

  private static int [] zzUnpackAction() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\55\0\132\0\207\0\264\0\341\0\u010e\0\u010e"+
    "\0\u010e\0\u013b\0\u0168\0\u010e\0\u010e\0\u010e\0\u0168\0\u0195"+
    "\0\u01c2\0\u01ef\0\u021c\0\u0249\0\u0276\0\u02a3\0\u02d0\0\u02fd"+
    "\0\u032a\0\u0357\0\u0384\0\u03b1\0\u03de\0\u040b\0\u0438\0\u0465"+
    "\0\u0492\0\u04bf\0\u04ec\0\u0519\0\u0546\0\u0573\0\u05a0\0\u010e"+
    "\0\u010e\0\u010e\0\u010e\0\u05cd\0\u010e\0\u010e\0\u010e\0\u010e"+
    "\0\u010e\0\u010e\0\u010e\0\u010e\0\u010e\0\u01ef\0\u05fa\0\u0627"+
    "\0\u0654\0\u0681\0\u06ae\0\u06db\0\u0708\0\u0735\0\u0762\0\u078f"+
    "\0\u07bc\0\u07e9\0\u0816\0\u0843\0\u0870\0\u089d\0\u08ca\0\u08f7"+
    "\0\u02a3\0\u0924\0\u0951\0\u097e\0\u09ab\0\u09d8\0\u0a05\0\u0a32"+
    "\0\u0a5f\0\u0a8c\0\u0ab9\0\u0ae6\0\u0b13\0\u0b40\0\u0b6d\0\u010e"+
    "\0\u010e\0\u010e\0\u010e\0\u010e\0\u010e\0\u0b9a\0\u0bc7\0\u01ef"+
    "\0\u06ae\0\u0bf4\0\u0c21\0\u0c4e\0\u0c7b\0\u0ca8\0\u0cd5\0\u0d02"+
    "\0\u0d2f\0\u0d5c\0\u0d89\0\u0db6\0\u0de3\0\u0e10\0\u0e3d\0\u0e6a"+
    "\0\u0e97\0\u0ec4\0\u0ef1\0\u0f1e\0\u0f4b\0\u0f78\0\u0fa5\0\u0fd2"+
    "\0\u0fff\0\u102c\0\u1059\0\u1086\0\u10b3\0\u10e0\0\u110d\0\u010e"+
    "\0\u113a\0\u0924\0\u1167\0\u1194\0\u11c1\0\u11ee\0\u121b\0\u1248"+
    "\0\u1275\0\u12a2\0\u12cf\0\u12fc\0\u1329\0\u1356\0\u1383\0\u13b0"+
    "\0\u13dd\0\u140a\0\u1437\0\u1464\0\u1491\0\u14be\0\u14eb\0\u1518";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\2\17"+
    "\4\26\1\7\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\26\1\36\1\26\1\37\1\40\1\26\1\41"+
    "\1\42\1\43\1\44\1\45\1\46\1\47\3\26\2\50"+
    "\2\7\1\50\1\51\17\50\1\52\27\50\2\53\2\7"+
    "\3\53\1\7\15\53\1\54\27\53\7\55\1\56\52\55"+
    "\1\57\1\55\1\60\15\55\1\61\13\55\1\62\2\55"+
    "\1\63\1\55\1\64\15\55\1\65\45\55\57\0\1\11"+
    "\72\0\1\15\45\0\1\15\6\0\1\15\46\0\1\15"+
    "\5\0\1\15\51\0\2\66\46\0\1\67\3\0\1\70"+
    "\3\0\1\15\47\0\1\66\1\0\2\71\3\0\1\72"+
    "\1\0\1\73\5\0\1\72\17\0\1\73\15\0\1\66"+
    "\1\0\2\25\3\0\1\72\7\0\1\72\37\0\2\26"+
    "\2\0\4\26\1\0\27\26\15\0\2\26\2\0\4\26"+
    "\1\0\21\26\1\74\5\26\15\0\2\26\2\0\4\26"+
    "\1\0\14\26\1\75\1\26\1\76\10\26\15\0\2\26"+
    "\2\0\4\26\1\0\1\77\6\26\1\100\4\26\1\101"+
    "\12\26\15\0\2\26\2\0\4\26\1\0\4\26\1\102"+
    "\7\26\1\103\12\26\15\0\2\26\2\0\4\26\1\0"+
    "\12\26\1\77\11\26\1\104\2\26\15\0\2\26\2\0"+
    "\4\26\1\0\1\105\11\26\1\106\1\26\1\107\4\26"+
    "\1\110\5\26\15\0\2\26\2\0\4\26\1\0\14\26"+
    "\1\74\12\26\15\0\2\26\2\0\4\26\1\0\5\26"+
    "\1\111\5\26\1\112\13\26\15\0\2\26\2\0\4\26"+
    "\1\0\14\26\1\113\12\26\15\0\2\26\2\0\4\26"+
    "\1\0\4\26\1\114\22\26\15\0\2\26\2\0\4\26"+
    "\1\0\16\26\1\115\10\26\15\0\2\26\2\0\4\26"+
    "\1\0\4\26\1\116\22\26\15\0\2\26\2\0\4\26"+
    "\1\0\7\26\1\117\1\120\7\26\1\121\2\26\1\122"+
    "\3\26\15\0\2\26\2\0\4\26\1\0\16\26\1\123"+
    "\6\26\1\124\1\26\15\0\2\26\2\0\4\26\1\0"+
    "\13\26\1\125\13\26\15\0\2\26\2\0\4\26\1\0"+
    "\14\26\1\126\12\26\15\0\2\26\2\0\4\26\1\0"+
    "\7\26\1\127\17\26\5\0\1\130\1\0\1\131\15\0"+
    "\1\132\13\0\1\133\2\0\1\134\1\0\1\135\6\0"+
    "\10\136\1\137\44\136\2\70\2\0\51\70\13\0\1\66"+
    "\1\0\2\71\3\0\1\72\7\0\1\72\33\0\2\140"+
    "\2\0\2\66\53\0\2\141\2\0\2\141\3\0\6\141"+
    "\36\0\2\26\2\0\4\26\1\0\20\26\1\142\6\26"+
    "\15\0\2\26\2\0\4\26\1\0\14\26\1\143\12\26"+
    "\15\0\2\26\2\0\4\26\1\0\4\26\1\144\22\26"+
    "\15\0\2\26\2\0\4\26\1\0\17\26\1\145\7\26"+
    "\15\0\2\26\2\0\4\26\1\0\1\146\26\26\15\0"+
    "\2\26\2\0\4\26\1\0\13\26\1\147\13\26\15\0"+
    "\2\26\2\0\4\26\1\0\5\26\1\150\21\26\15\0"+
    "\2\26\2\0\4\26\1\0\21\26\1\151\5\26\15\0"+
    "\2\26\2\0\4\26\1\0\20\26\1\152\6\26\15\0"+
    "\2\26\2\0\4\26\1\0\12\26\1\77\14\26\15\0"+
    "\2\26\2\0\4\26\1\0\14\26\1\153\12\26\15\0"+
    "\2\26\2\0\4\26\1\0\16\26\1\154\10\26\15\0"+
    "\2\26\2\0\4\26\1\0\13\26\1\155\13\26\15\0"+
    "\2\26\2\0\4\26\1\0\20\26\1\111\6\26\15\0"+
    "\2\26\2\0\4\26\1\0\13\26\1\156\13\26\15\0"+
    "\2\26\2\0\4\26\1\0\23\26\1\111\3\26\15\0"+
    "\2\26\2\0\4\26\1\0\10\26\1\157\16\26\15\0"+
    "\2\26\2\0\4\26\1\0\2\26\1\160\12\26\1\161"+
    "\2\26\1\162\6\26\15\0\2\26\2\0\4\26\1\0"+
    "\14\26\1\163\12\26\15\0\2\26\2\0\4\26\1\0"+
    "\6\26\1\164\17\26\1\165\15\0\2\26\2\0\4\26"+
    "\1\0\1\166\15\26\1\167\10\26\15\0\2\26\2\0"+
    "\4\26\1\0\10\26\1\170\16\26\15\0\2\26\2\0"+
    "\4\26\1\0\21\26\1\145\5\26\15\0\2\26\2\0"+
    "\4\26\1\0\15\26\1\171\11\26\15\0\2\26\2\0"+
    "\4\26\1\0\10\26\1\172\7\26\1\173\6\26\15\0"+
    "\2\26\2\0\4\26\1\0\10\26\1\174\1\26\1\175"+
    "\14\26\15\0\2\26\2\0\4\26\1\0\10\26\1\176"+
    "\16\26\10\136\1\177\44\136\10\0\1\137\3\0\1\200"+
    "\55\0\2\26\2\0\4\26\1\0\14\26\1\111\12\26"+
    "\15\0\2\26\2\0\4\26\1\0\12\26\1\111\14\26"+
    "\15\0\2\26\2\0\4\26\1\0\1\201\26\26\15\0"+
    "\2\26\2\0\4\26\1\0\4\26\1\111\22\26\15\0"+
    "\2\26\2\0\4\26\1\0\16\26\1\111\10\26\15\0"+
    "\2\26\2\0\4\26\1\0\17\26\1\202\1\203\6\26"+
    "\15\0\2\26\2\0\4\26\1\0\1\204\26\26\15\0"+
    "\2\26\2\0\4\26\1\0\1\26\1\176\25\26\15\0"+
    "\2\26\2\0\4\26\1\0\4\26\1\205\22\26\15\0"+
    "\2\26\2\0\4\26\1\0\1\202\26\26\15\0\2\26"+
    "\2\0\4\26\1\0\4\26\1\206\22\26\15\0\2\26"+
    "\2\0\4\26\1\0\2\26\1\207\24\26\15\0\2\26"+
    "\2\0\4\26\1\0\6\26\1\111\20\26\15\0\2\26"+
    "\2\0\4\26\1\0\13\26\1\210\13\26\15\0\2\26"+
    "\2\0\4\26\1\0\14\26\1\211\12\26\15\0\2\26"+
    "\2\0\4\26\1\0\4\26\1\153\22\26\15\0\2\26"+
    "\2\0\4\26\1\0\21\26\1\205\5\26\15\0\2\26"+
    "\2\0\4\26\1\0\16\26\1\202\10\26\15\0\2\26"+
    "\2\0\4\26\1\0\13\26\1\212\13\26\15\0\2\26"+
    "\2\0\4\26\1\0\4\26\1\213\22\26\15\0\2\26"+
    "\2\0\4\26\1\0\20\26\1\214\6\26\15\0\2\26"+
    "\2\0\4\26\1\0\10\26\1\113\16\26\15\0\2\26"+
    "\2\0\4\26\1\0\20\26\1\215\6\26\15\0\2\26"+
    "\2\0\4\26\1\0\4\26\1\216\22\26\15\0\2\26"+
    "\2\0\4\26\1\0\14\26\1\217\12\26\15\0\2\26"+
    "\2\0\4\26\1\0\10\26\1\143\16\26\15\0\2\26"+
    "\2\0\4\26\1\0\3\26\1\111\23\26\15\0\2\26"+
    "\2\0\4\26\1\0\1\220\26\26\15\0\2\26\2\0"+
    "\4\26\1\0\12\26\1\145\14\26\10\136\1\177\3\136"+
    "\1\200\40\136\15\0\2\26\2\0\4\26\1\0\11\26"+
    "\1\111\15\26\15\0\2\26\2\0\4\26\1\0\10\26"+
    "\1\221\16\26\15\0\2\26\2\0\4\26\1\0\21\26"+
    "\1\222\5\26\15\0\2\26\2\0\4\26\1\0\16\26"+
    "\1\217\10\26\15\0\2\26\2\0\4\26\1\0\1\215"+
    "\26\26\15\0\2\26\2\0\4\26\1\0\20\26\1\223"+
    "\6\26\15\0\2\26\2\0\4\26\1\0\20\26\1\224"+
    "\6\26\15\0\2\26\2\0\4\26\1\0\16\26\1\174"+
    "\10\26\15\0\2\26\2\0\4\26\1\0\4\26\1\174"+
    "\22\26\15\0\2\26\2\0\4\26\1\0\14\26\1\225"+
    "\12\26\15\0\2\26\2\0\4\26\1\0\10\26\1\226"+
    "\16\26\15\0\2\26\2\0\4\26\1\0\2\26\1\227"+
    "\24\26\15\0\2\26\2\0\4\26\1\0\3\26\1\230"+
    "\23\26\15\0\2\26\2\0\4\26\1\0\13\26\1\111"+
    "\13\26\15\0\2\26\2\0\4\26\1\0\20\26\1\127"+
    "\6\26\15\0\2\26\2\0\4\26\1\0\13\26\1\123"+
    "\13\26\15\0\2\26\2\0\4\26\1\0\12\26\1\202"+
    "\14\26\15\0\2\26\2\0\4\26\1\0\10\26\1\172"+
    "\16\26\15\0\2\26\2\0\4\26\1\0\12\26\1\217"+
    "\14\26\15\0\2\26\2\0\4\26\1\0\5\26\1\111"+
    "\21\26\15\0\2\26\2\0\4\26\1\0\2\26\1\111"+
    "\24\26\15\0\2\26\2\0\4\26\1\0\7\26\1\111"+
    "\17\26\15\0\2\26\2\0\4\26\1\0\4\26\1\225"+
    "\22\26";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5445];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\6\0\3\11\2\1\3\11\31\1\4\11\1\1\11\11"+
    "\1\1\1\0\1\1\3\0\34\1\6\11\3\0\36\1"+
    "\1\0\1\11\30\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[152];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    StringBuffer string = new StringBuffer();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  myScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Symbol CScannerFunction() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return new Symbol(yytext(),100);
            }
            // fall through
          case 31: break;
          case 2:
            { return new Symbol(yytext(), 8);
            }
            // fall through
          case 32: break;
          case 3:
            { return new Symbol(yytext(), 9);
            }
            // fall through
          case 33: break;
          case 4:
            { string.setLength(0); string.append(yytext()); yybegin(STRING);
            }
            // fall through
          case 34: break;
          case 5:
            { return new Symbol(yytext(),11);
            }
            // fall through
          case 35: break;
          case 6:
            { string.setLength(0); string.append(yytext()); yybegin(CHAR);
            }
            // fall through
          case 36: break;
          case 7:
            { return new Symbol(yytext(), 3);
            }
            // fall through
          case 37: break;
          case 8:
            { return new Symbol(yytext(), 2);
            }
            // fall through
          case 38: break;
          case 9:
            { string.append(yytext());
            }
            // fall through
          case 39: break;
          case 10:
            { yybegin(YYINITIAL); string.append(yytext()); return new Symbol(string.toString(), 5);
            }
            // fall through
          case 40: break;
          case 11:
            { yybegin(SPECIALCHARSTR); return new Symbol(string.toString(), 5);
            }
            // fall through
          case 41: break;
          case 12:
            { string.append(yytext()); yybegin(ENDCHAR);
            }
            // fall through
          case 42: break;
          case 13:
            { throw new Error("Illegal character <"+yytext()+">"+" Line: " + yyline + ", Column: " + yycolumn);
            }
            // fall through
          case 43: break;
          case 14:
            { yybegin(YYINITIAL); string.append(yytext()); return new Symbol(string.toString(), 6);
            }
            // fall through
          case 44: break;
          case 15:
            { yybegin(STRING); string.setLength(0); return new Symbol("\\\"", 10);
            }
            // fall through
          case 45: break;
          case 16:
            { yybegin(STRING); string.setLength(0); return new Symbol("\\\'", 10);
            }
            // fall through
          case 46: break;
          case 17:
            { yybegin(STRING); string.setLength(0); return new Symbol("\\\\", 10);
            }
            // fall through
          case 47: break;
          case 18:
            { yybegin(STRING); string.setLength(0); return new Symbol("\\n", 10);
            }
            // fall through
          case 48: break;
          case 19:
            { yybegin(STRING); string.setLength(0); return new Symbol("\\r", 10);
            }
            // fall through
          case 49: break;
          case 20:
            { yybegin(STRING); string.setLength(0); return new Symbol("\\t", 10);
            }
            // fall through
          case 50: break;
          case 21:
            { yybegin(YYINITIAL); string.append(yytext()); return new Symbol(string.toString(), 10);
            }
            // fall through
          case 51: break;
          case 22:
            { return new Symbol(yytext(), 4);
            }
            // fall through
          case 52: break;
          case 23:
            { return new Symbol(yytext(), 7);
            }
            // fall through
          case 53: break;
          case 24:
            { return new Symbol(yytext(), 1);
            }
            // fall through
          case 54: break;
          case 25:
            { string.append("\\\""); yybegin(SPECIALCHAR);
            }
            // fall through
          case 55: break;
          case 26:
            { string.append("\\\'"); yybegin(SPECIALCHAR);
            }
            // fall through
          case 56: break;
          case 27:
            { string.append("\\\\"); yybegin(SPECIALCHAR);
            }
            // fall through
          case 57: break;
          case 28:
            { string.append("\\n"); yybegin(SPECIALCHAR);
            }
            // fall through
          case 58: break;
          case 29:
            { string.append("\\r"); yybegin(SPECIALCHAR);
            }
            // fall through
          case 59: break;
          case 30:
            { string.append("\\t"); yybegin(SPECIALCHAR);
            }
            // fall through
          case 60: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
